CREATE SCHEMA "data";
CREATE SCHEMA "app";

DROP TABLE "public"."User";

ALTER TYPE "public"."YearPeriods" SET SCHEMA "data";
ALTER TYPE "public"."CourseOfferingPeriod" SET SCHEMA "data";
ALTER TYPE "public"."CourseEvaluationMode" SET SCHEMA "data";
ALTER TYPE "public"."CatalogCoursePrerequisiteKind" SET SCHEMA "data";
ALTER TYPE "public"."CurriculumSuggestionType" SET SCHEMA "data";
ALTER TYPE "public"."CourseBlockType" SET SCHEMA "data";
ALTER TYPE "public"."CourseRequirementType" SET SCHEMA "data";
ALTER TYPE "public"."DayOfWeek" SET SCHEMA "data";
ALTER TYPE "public"."MealPeriod" SET SCHEMA "data";
ALTER TYPE "public"."DietaryOption" SET SCHEMA "data";
ALTER TYPE "public"."MealStatus" SET SCHEMA "data";

ALTER TYPE "public"."AuthUserStatus" SET SCHEMA "app";
ALTER TYPE "public"."AuthRole" SET SCHEMA "app";
ALTER TYPE "public"."Capability" SET SCHEMA "app";
ALTER TYPE "public"."StudentCapability" SET SCHEMA "app";
ALTER TYPE "public"."StudentFriendshipStatus" SET SCHEMA "app";
ALTER TYPE "public"."StudentCourseAttemptStatus" SET SCHEMA "app";
ALTER TYPE "public"."PeriodPlanningGuideMode" SET SCHEMA "app";
ALTER TYPE "public"."PeriodPlanningCurriculumSource" SET SCHEMA "app";

ALTER TABLE "public"."Unit" SET SCHEMA "data";
ALTER TABLE "public"."Coordinator" SET SCHEMA "data";
ALTER TABLE "public"."Prefixes" SET SCHEMA "data";
ALTER TABLE "public"."Course" SET SCHEMA "data";
ALTER TABLE "public"."Catalog" SET SCHEMA "data";
ALTER TABLE "public"."CatalogCourse" SET SCHEMA "data";
ALTER TABLE "public"."CatalogCoursePrerequisiteGroup" SET SCHEMA "data";
ALTER TABLE "public"."CatalogCoursePrerequisiteItem" SET SCHEMA "data";
ALTER TABLE "public"."Program" SET SCHEMA "data";
ALTER TABLE "public"."Specialization" SET SCHEMA "data";
ALTER TABLE "public"."Language" SET SCHEMA "data";
ALTER TABLE "public"."CatalogProgram" SET SCHEMA "data";
ALTER TABLE "public"."CatalogSpecialization" SET SCHEMA "data";
ALTER TABLE "public"."CatalogLanguage" SET SCHEMA "data";
ALTER TABLE "public"."CurriculumSuggestion" SET SCHEMA "data";
ALTER TABLE "public"."SemesterSuggestion" SET SCHEMA "data";
ALTER TABLE "public"."SuggestionCourse" SET SCHEMA "data";
ALTER TABLE "public"."CourseBlock" SET SCHEMA "data";
ALTER TABLE "public"."CourseRequirement" SET SCHEMA "data";
ALTER TABLE "public"."StudyPeriod" SET SCHEMA "data";
ALTER TABLE "public"."Professor" SET SCHEMA "data";
ALTER TABLE "public"."Room" SET SCHEMA "data";
ALTER TABLE "public"."Class" SET SCHEMA "data";
ALTER TABLE "public"."ClassSchedule" SET SCHEMA "data";
ALTER TABLE "public"."DailyMenu" SET SCHEMA "data";
ALTER TABLE "public"."Meal" SET SCHEMA "data";
ALTER TABLE "public"."MealItem" SET SCHEMA "data";
ALTER TABLE "public"."MealObservation" SET SCHEMA "data";
ALTER TABLE "public"."MealServiceNote" SET SCHEMA "data";
ALTER TABLE "public"."CalendarEvent" SET SCHEMA "data";
ALTER TABLE "public"."CalendarTag" SET SCHEMA "data";
ALTER TABLE "public"."_CalendarEventToCalendarTag" SET SCHEMA "data";
ALTER TABLE "public"."_ClassToProfessor" SET SCHEMA "data";
ALTER TABLE "public"."_ClassToPeriodPlanning" SET SCHEMA "data";

ALTER TABLE "public"."AuthUser" SET SCHEMA "app";
ALTER TABLE "public"."AuthUserRole" SET SCHEMA "app";
ALTER TABLE "public"."AuthUserCapability" SET SCHEMA "app";
ALTER TABLE "public"."Student" SET SCHEMA "app";
ALTER TABLE "public"."StudentFriendship" SET SCHEMA "app";
ALTER TABLE "public"."BotGrant" SET SCHEMA "app";
ALTER TABLE "public"."StudentCourseAttempt" SET SCHEMA "app";
ALTER TABLE "public"."ProfessorEvaluation" SET SCHEMA "app";
ALTER TABLE "public"."StudentAbsence" SET SCHEMA "app";
ALTER TABLE "public"."Curriculum" SET SCHEMA "app";
ALTER TABLE "public"."CurriculumCourse" SET SCHEMA "app";
ALTER TABLE "public"."CurriculumPeriod" SET SCHEMA "app";
ALTER TABLE "public"."PeriodPlanning" SET SCHEMA "app";
ALTER TABLE "public"."PeriodPlanningManualCourse" SET SCHEMA "app";
